version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    commit-message:
      prefix: Bump
    schedule:
      interval: "daily"
    assignees:
      - 'mleutenegger'
  - package-ecosystem: npm
    directory: "/"
    commit-message:
      prefix: Bump
    schedule:
      interval: "daily"
    assignees:
      - 'mleutenegger'
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: Bump
    schedule:
      interval: "daily"
    assignees:
      - 'mleutenegger'
